- src/components/Tertiary-button/Tertiary-button.js
https://ctl.atlassian.net/browse/FSPE-7282
> [FSPE-7282] Fixed portal tertiary button styles

- package-lock.json
- package.json
- src/components/Popover/Popover.js
- src/components/UXPinWrapper/UXPinWrapper.js
- uxpin.config.js
- yarn.lock
https://ctl.atlassian.net/browse/FSPE-7192
> [FSPE-7192] Added support of Popover component

- package-lock.json
- package.json
- src/components/Icon-button/Icon-button.js
- src/components/Search-input/Search-input.js
- src/components/UXPinWrapper/UXPinWrapper.js
- uxpin.config.js
https://ctl.atlassian.net/browse/FSPE-7556
> [FSPE-7555] Added support of Search Input component

- src/components/Alert/Alert.js
@janibolkvadze Please review and approve
> [FSDE-663] : Alert component portal changes, adding test in progress component

- src/components/Badge/Badge.js
- src/components/Brand/Brand.js
- src/components/Date-picker/Date-picker.js
- src/components/Icon-button/Icon-button.js
- src/components/Icon/Icon.js
- src/components/Marketing-icon/Marketing-icon.js
- src/components/Number-input/Number-input.js
- src/components/Primary-button/Primary-button.js
- src/components/Secondary-button/Secondary-button.js
- src/components/Spinner/Spinner.js
- src/components/Tertiary-button/Tertiary-button.js
- src/components/Time-picker/Time-picker.js
@riya-abraham01 
https://ctl.atlassian.net/browse/FSDE-734
> [FSDE-734] Added support of uxpinRef to each component

- src/components/Badge/Badge.js
- src/components/Brand/Brand.js
- src/components/Number-input/Number-input.js
- src/components/Pagination/Pagination.js
- src/components/Pagination/presets/0-default.jsx
- src/components/Secondary-button/Secondary-button.js
- src/components/Tabs/Tabs.js
@riya-abraham01 
https://ctl.atlassian.net/browse/FSDE-761
> [FSDE-761] Change pagination component compact   results default properties and update brand component sizes

- package.json
- src/components/Page-Title/Page-Title.js
- src/components/Page-Title/presets/0-default.jsx
- src/components/Tabs/Tabs.js
- uxpin.config.js
> [FSDE-702] Page Title new component code changes

- src/components/Page-Title/Page-Title.js
> [FIX] Disabled unnecessary event handler on Page Title

- src/components/Pagination/Pagination.js
- src/components/Picker-group/Picker-group.js
- src/components/StatCompact/StatCompact.js
https://ctl.atlassian.net/browse/FSDE-3688
> [FSDE-3688] Adjusted Container Box sizes

- package.json
- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownMenu/DropdownMenu.js
- src/components/Picker-group/Picker-group.js
- src/components/Tabs/Tabs.js
- src/constants/classes.js
- Fix to update dropdown base Text when the user updates the text.
- Add fluid capability to picker group component.
- Add flat and solid vertical capability to Tabs component.
> [FSDE-23037] UX Pin Enhancements and Fixes

- src/components/Checkbox/Checkbox.js
- src/components/Date-picker/Date-picker.js
- src/components/Flat-button/Flat-button.js
- src/components/Flat-button/presets/0-default.jsx
- src/components/Icon/Icon.js
- src/components/Info-icon/Info-icon.js
- src/components/Info-icon/presets/0-default.jsx
- src/components/Label/Label.js
- src/components/Number-input/Number-input.js
- src/components/PhoneInput/PhoneInput.js
- src/components/Picker-group/Picker-group.js
- src/components/Picker-multi/PickerMulti.js
- src/components/Picker-single/PickerSingle.js
- src/components/Primary-button/Primary-button.js
- src/components/Radio/Radio.js
- src/components/Select/Select.js
- src/components/Text-input/Text-input.js
- src/components/Textarea/Textarea.js
- src/components/Time-picker/Time-picker.js
- src/constants/constants.js
- uxpin.config.js
- Add popover functionality to info icon for form elements with info icon feature.
- Add click interaction to info icon component.
- Implement flat button component.
- Add text field to text area component.
- Bump chi version to 5.30.0
> Popover addition in form elements and flat button implementation

- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownBase/presets/0-default.jsx
- src/components/Flat-button/Flat-button.js
- src/components/Primary-button/Primary-button.js
- src/components/Secondary-button/Secondary-button.js
- src/components/Tabs/Tabs.js
- src/components/Tertiary-button/Tertiary-button.js
- Ability to add left and right icons for Flat button component.
- Tertiary button is limited to only XS and Primary, Secondary, Flat are limited to only XS and MD size with MD as default.
- Change default animate chevron to false for dropdown base component.
> [FSDE-31141] UxPin Enhancements

- package.json
- src/components/Radio/Radio.js
- src/components/Radio/presets/0-default.jsx
- src/constants/constants.js
- Also bumped chi version to 5.31.0
> [FSDE-31283] Implement layout field for radio component - Inline and vertical

- package.json
- src/components/Text/Text.js
- Also bumped up version tag to 1.0.36
> [FSDE-31323] Change p to div tag to fix issue in Text component

- package.json
- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownBase/presets/0-default.jsx
- src/components/DropdownMenu/DropdownMenu.js
- src/components/Text/Text.js
- src/components/Text/presets/0-default.jsx
- Also fixes dropdown menu width to match the given specified width property
- Updated Text Align property to align Text to (Left, center and right) Left as Default
- Bumped version to 1.0.36
[FSDE-31323]: https://ctl.atlassian.net/browse/FSDE-31323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FSDE-31180] Drop down base refactor to consume web component

- package.json
- src/components/DropdownBase/DropdownBase.js
- src/components/Select/Select.js
- Also fixes the select interaction issue
- Update tag version to 1.0.39
> [FSDE-31344] Fix dropdown base text sync in UXPin

- package.json
- src/components/Alert/Alert.js
- src/components/DropdownMenu/DropdownMenu.js
- src/constants/constants.js
- As per Tom, also reverting back earlier changes to include auto scroll functionality for dropdown list items dropdown menu height to align with todays chi behavior.
- Also bumped package version to 1.0.43 and chi version to 5.37.0
> [DPEDE-489] Add closable functionality to Alert component in UXpin

- src/components/Alert/Alert.js
- src/components/Link/Link.js
- As per Tom, removed the comments which are rendering as help info text on CTA which is not required.
> [DPEDE-503] Add close click interaction functionality to Alert component

- src/components/PhoneInput/PhoneInput.js
- src/components/PhoneInput/presets/0-default.jsx
- src/components/Progress/Progress.js
- src/components/Progress/presets/0-default.jsx
- src/components/Text-input/Text-input.js
- Also consists of updates related to progress component to hide states and remove success state as default.
- Renaming and reordering of property names in Phone and Text Input components.
> [DPEDE-591] Fix country code formatting for phone input

- src/components/Alert/Alert.js
- src/constants/classes.js
- Also refactored Alert component to consume chi-alert web component
> [DPEDE-904] Add capability for active show/hide for closable alert

- package.json
- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownBase/presets/0-default.jsx
- src/components/DropdownMenu/DropdownMenu.js
- src/components/DropdownSearchItems/DropdownSearchItems.js
- src/components/DropdownSearchItems/presets/0-default.jsx
- Added xs size to dropdown base component.
- Implemented info icon popover functionality for dropdown base and search items.
- Changed default buttonType to outline.
- Added 5 more fields for items, icons and selections for dropdown search component.
> [DPEDE-907] Implement enhancements for dropdown components

- package.json
https://ctl.atlassian.net/browse/DPEDE-948
> [DPEDE-948] Add versioning tags for UXPin merge push to prod command

- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownBase/presets/0-default.jsx
- src/components/DropdownMenu/DropdownMenu.js
- src/components/DropdownSearchItems/DropdownSearchItems.js
- src/components/DropdownSearchItems/presets/0-default.jsx
- Added xs size to dropdown base component.
- Implemented info icon popover functionality for dropdown base and search items.
- Reverted default buttonType to flat.
- Implemented showLabel boolean which will enable Label component over dropdown.
- Added 5 more fields for items, icons and selections for dropdown search component and fix case sensitive issue.
> [DPEDE-907] Implement changes for dropdown enhancements

- src/components/Alert/Alert.js
- Consists of properties enhancements as recommended by Tom
- Handles title undefined issue
> Review updates for padding fix and property adjustments for Alert component

- src/components/DropdownBase/DropdownBase.js
- src/components/DropdownMenu/DropdownMenu.js
- Also fixes the existing production issue for item title and description alignment issue. Attached are the before and after images for dropdown with description.
- Removed app switcher property which is no more needed.
- Removed margin right property which is not needed for icon left.[
](url)
> Updates for existing dropdown base component

- .eslintrc
- src/components/Popover-buttons/PopoverButtons.js
- src/components/Popover-buttons/presets/0-default.jsx
- src/components/Popover-headings/PopoverHeadings.js
- src/components/Popover-headings/presets/0-default.jsx
- src/components/Popover-images/PopoverImages.js
- src/components/Popover-images/presets/0-default.jsx
- src/components/Popover-links/PopoverLinks.js
- src/components/Popover-links/presets/0-default.jsx
- src/components/Popover-tabs/PopoverTabs.js
- src/components/Popover-tabs/presets/0-default.jsx
- src/components/Popover/Popover.js
- src/components/Popover/presets/0-default.jsx
- src/components/Search-input/Search-input.js
- uxpin.config.js
- Also includes fix for search input component outline selection
> [DPEDE-1418] Create accessibility popovers in UXPin

- src/components/Picker-group/Picker-group.js
Added xs, sm, md(default), lg sizes as described in https://lib.lumen.com/chi/5.67.0/components/picker-group/?theme=Portal#sizes-1
> [DPEDE-1965] Added size property do picker group component

- src/components/DropdownIconWc/DropdownIconWc.js
- src/components/Icon-button/Icon-button.js
- Changed Icon button component to use web-component
- Added conditional showting tooltip in dropdownIconWc
> [DPEDE-2565] Fixed tooltips  in dropdownIconWc and IconButton
